name: eServerCommands
version: 0.00.002A
main: org.kevinjss1.bukkit.eServerCommands.main.Main
author: kevinjss1
description: A assortment of basic server commands for your players and admins.
 
commands:
    heal:
        aliases: [h, givehealth]
        description: Heal.
    op:
        description: Op a player.
    deop:
        description: Deop a player.
    eversion:
        aliases: [ev, ever]
        description: View version information.